In [3]:
import tensorflow as tf


In [4]:
a=tf.constant(3)
b=tf.constant(4)
c= a+b
print(c)

tf.Tensor(7, shape=(), dtype=int32)


Layers and models

In [6]:
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(10,activation='relu',input_shape=(5,)),
    Dense(1)  # each Dense layer represents a fully connected layer in a neural network
])

Compilation and Training

In [7]:
model.compile(optimizer='adam',loss='mse')
#optimizer adjusts weights (eg:Adam,SGD)
# loss Measures model error(eg:Mean Squared Error)


In [8]:
import numpy as np
X= np.random.rand(100,5)
y=np.random.rand(100,1)

model.fit(X,y,epochs=10
         )

Epoch 1/10

4/4 [==============================] - 1s 6ms/step - loss: 0.2869
Epoch 2/10
4/4 [==============================] - 0s 2ms/step - loss: 0.2525
Epoch 3/10
4/4 [==============================] - 0s 4ms/step - loss: 0.2243
Epoch 4/10
4/4 [==============================] - 0s 5ms/step - loss: 0.2024
Epoch 5/10
4/4 [==============================] - 0s 3ms/step - loss: 0.1848
Epoch 6/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1734
Epoch 7/10
4/4 [==============================] - 0s 5ms/step - loss: 0.1649
Epoch 8/10
4/4 [==============================] - 0s 5ms/step - loss: 0.1600
Epoch 9/10
4/4 [==============================] - 0s 5ms/step - loss: 0.1556
Epoch 10/10
4/4 [==============================] - 0s 4ms/step - loss: 0.1532


In [11]:
print(X)

[[3.78436492e-01 2.73318671e-01 4.95823669e-01 9.61033434e-01
  8.31135451e-01]
 [6.42115945e-01 7.20632785e-01 8.99515548e-02 3.18356382e-01
  1.10811880e-01]
 [2.97991930e-01 3.60677668e-01 9.46166253e-01 2.99156757e-01
  8.36943097e-01]
 [1.16837912e-01 9.34910329e-01 7.68001073e-01 3.16560814e-01
  2.52814816e-01]
 [8.69328494e-01 9.25253845e-01 7.05880919e-01 3.26088113e-01
  1.65445816e-01]
 [6.94905772e-02 6.61016400e-01 5.16364630e-01 5.14325035e-03
  7.44151762e-01]
 [3.39443676e-01 7.23485408e-01 7.21938808e-01 8.46407379e-02
  7.73131623e-01]
 [3.38872853e-01 3.71039322e-01 7.48224611e-01 4.69796189e-01
  4.10851967e-01]
 [5.98040134e-02 1.65756800e-01 3.89160369e-01 6.40526982e-01
  3.57743060e-01]
 [7.61896228e-01 9.81680024e-01 4.23334386e-01 3.64395434e-01
  7.20698106e-01]
 [2.08007077e-01 5.18448881e-01 6.76933094e-01 7.85644707e-01
  7.38730606e-01]
 [2.66014357e-01 5.02797887e-01 3.58998855e-01 8.59976272e-01
  7.03604662e-01]
 [8.44495681e-01 2.43111356e-01 5.249968

In [10]:
new_data = np.random.rand(3,5)

# predict using the trained model
predictions = model.predict(new_data)

print("New input data: \n",new_data)
print("predictions:\n",predictions)

1/1 [==============================] - 0s 20ms/step
New input data: 
 [[0.7673098  0.4721237  0.13733262 0.81718522 0.40240104]
 [0.43082603 0.04362743 0.05435899 0.83340319 0.37898897]
 [0.14169221 0.75865385 0.80054019 0.02969213 0.61803096]]
predictions:
 [[0.50934815]
 [0.11900477]
 [0.48258978]]


Binary classification Neural Network

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense




In [14]:
# sample data
X = np.random.rand(100,5)
y=np.random.randint(0,2,size=(100,1))

In [17]:
model = Sequential([
    Dense(16,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='sigmoid')
])

In [18]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [19]:
model.fit(X,y,epochs=20,batch_size=10)


Epoch 1/20

10/10 [==============================] - 1s 3ms/step - loss: 0.6925 - accuracy: 0.5000
Epoch 2/20
10/10 [==============================] - 0s 3ms/step - loss: 0.6915 - accuracy: 0.5700
Epoch 3/20
10/10 [==============================] - 0s 2ms/step - loss: 0.6912 - accuracy: 0.5500
Epoch 4/20
10/10 [==============================] - 0s 2ms/step - loss: 0.6906 - accuracy: 0.5800
Epoch 5/20
10/10 [==============================] - 0s 3ms/step - loss: 0.6902 - accuracy: 0.6000
Epoch 6/20
10/10 [==============================] - 0s 2ms/step - loss: 0.6897 - accuracy: 0.6000
Epoch 7/20
10/10 [==============================] - 0s 2ms/step - loss: 0.6893 - accuracy: 0.5800
Epoch 8/20
10/10 [==============================] - 0s 2ms/step - loss: 0.6889 - accuracy: 0.5800
Epoch 9/20
10/10 [==============================] - 0s 3ms/step - loss: 0.6885 - accuracy: 0.5700
Epoch 10/20
10/10 [==============================] - 0s 3ms/step - loss: 0.6878 - accuracy: 0.5900
Epoch 11/20
10/10 

In [21]:

new_data =np.random.rand(3,5)
pred_prob=model.predict(new_data)
pred_classes= (pred_prob>0.5).astype(int)
print(pred_prob)
print(pred_classes)

1/1 [==============================] - 0s 20ms/step
[[0.49570242]
 [0.5209047 ]
 [0.48667127]]
[[0]
 [1]
 [0]]


Multiclass Classification with Iris Dataset

In [23]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [28]:
iris = load_iris()
X=iris.data
y=iris.target

scaler = StandardScaler()
X=scaler.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)


In [24]:
model = Sequential([
    Dense(16,activation='relu',input_shape=(4,))
    ,
    Dense(12,activation='relu'),
    Dense(3,activation='softmax') #softmax used for multiclass calssification
])

In [25]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [29]:
model.fit(X_train,y_train,epochs=50,batch_size=8)

Epoch 1/50
15/15 [==============================] - 1s 2ms/step - loss: 1.0402 - accuracy: 0.4417
Epoch 2/50
15/15 [==============================] - 0s 2ms/step - loss: 0.9721 - accuracy: 0.6000
Epoch 3/50
15/15 [==============================] - 0s 3ms/step - loss: 0.9107 - accuracy: 0.6583
Epoch 4/50
15/15 [==============================] - 0s 2ms/step - loss: 0.8537 - accuracy: 0.6667
Epoch 5/50
15/15 [==============================] - 0s 2ms/step - loss: 0.7949 - accuracy: 0.6667
Epoch 6/50
15/15 [==============================] - 0s 2ms/step - loss: 0.7363 - accuracy: 0.6833
Epoch 7/50
15/15 [==============================] - 0s 2ms/step - loss: 0.6766 - accuracy: 0.7083
Epoch 8/50
15/15 [==============================] - 0s 2ms/step - loss: 0.6142 - accuracy: 0.7750
Epoch 9/50
15/15 [==============================] - 0s 2ms/step - loss: 0.5596 - accuracy: 0.7917
Epoch 10/50
15/15 [==============================] - 0s 2ms/step - loss: 0.5109 - accuracy: 0.8000
Epoch 11/50
15/15 [

In [30]:
loss,accuracy = model.evaluate(X_test,y_test)
print(accuracy)

1/1 [==============================] - 0s 140ms/step - loss: 0.0802 - accuracy: 1.0000
1.0


In [31]:
new_samples = np.array([[5.1, 3.5, 1.4, 0.2],   # Likely Setosa
                        [6.5, 3.0, 5.5, 1.8]])  # Likely Virginica
new_samples = scaler.transform(new_samples)    # Don't forget to scale

pred_probs = model.predict(new_samples)
pred_classes = np.argmax(pred_probs, axis=1)

print("Predicted Class Indices:", pred_classes)
print("Predicted Class Labels:", [iris.target_names[i] for i in pred_classes])


1/1 [==============================] - 0s 50ms/step
Predicted Class Indices: [0 2]
Predicted Class Labels: ['setosa', 'virginica']


Wine Dataset

In [5]:
from sklearn.datasets import load_wine
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [13]:
wine=load_wine()
X=wine.data
y=wine.target
print(X)
X=StandardScaler().fit_transform(X)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [7]:
model =Sequential([
    Dense(16,activation='relu'),`b
    Dense(8,activation='relu'),
    Dense(3,activation='softmax')
])

In [8]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [10]:
model.fit(X_train,y_train,epochs=50,batch_size=8)

Epoch 1/50


18/18 [==============================] - 1s 3ms/step - loss: 0.8981 - accuracy: 0.6127
Epoch 2/50
18/18 [==============================] - 0s 2ms/step - loss: 0.7812 - accuracy: 0.7394
Epoch 3/50
18/18 [==============================] - 0s 3ms/step - loss: 0.6851 - accuracy: 0.8099
Epoch 4/50
18/18 [==============================] - 0s 2ms/step - loss: 0.6032 - accuracy: 0.8451
Epoch 5/50
18/18 [==============================] - 0s 3ms/step - loss: 0.5371 - accuracy: 0.8944
Epoch 6/50
18/18 [==============================] - 0s 3ms/step - loss: 0.4777 - accuracy: 0.9155
Epoch 7/50
18/18 [==============================] - 0s 3ms/step - loss: 0.4206 - accuracy: 0.9225
Epoch 8/50
18/18 [==============================] - 0s 3ms/step - loss: 0.3667 - accuracy: 0.9225
Epoch 9/50
18/18 [==============================] - 0s 2ms/step - loss: 0.3161 - accuracy: 0.9507
Epoch 10/50
18/18 [==============================] - 0s 4ms/step - loss: 0.2734 - accuracy: 0.9577
Epoch 11/50
18/18

In [12]:
loss,acc=model.evaluate(X_test,y_test)
print(acc)

2/2 [==============================] - 0s 4ms/step - loss: 0.0043 - accuracy: 1.0000
1.0


Convolutional Neural Network

CNN for Image Classification(MNIST)

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Flatten,Dense
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [16]:
(X_train,y_train),(X_test,y_test) = mnist.load_data()

X_train = X_train.reshape(-1,28,28,1)/255.0
X_test = X_test.reshape(-1,28,28,1)/255.0

y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)

In [19]:
model = Sequential([
    Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    MaxPooling2D((2,2)),
    
    Conv2D(64,(3,3),activation='relu'),
    MaxPooling2D((2,2)),
    
    Flatten(),
    Dense(64,activation='relu'),
    Dense(10,activation='softmax')
])

In [20]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [27]:
model.fit(X_train[:100],y_train_cat[:100],epochs=5,batch_size=10)

Epoch 1/5
10/10 [==============================] - 0s 7ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 2/5
10/10 [==============================] - 0s 8ms/step - loss: 9.6721e-04 - accuracy: 1.0000
Epoch 3/5
10/10 [==============================] - 0s 7ms/step - loss: 4.8538e-04 - accuracy: 1.0000
Epoch 4/5
10/10 [==============================] - 0s 6ms/step - loss: 3.1682e-04 - accuracy: 1.0000
Epoch 5/5
10/10 [==============================] - 0s 6ms/step - loss: 2.4345e-04 - accuracy: 1.0000


In [28]:
loss,acc = model.evaluate(X_test,y_test_cat)
print(acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.0316 - accuracy: 0.9907
0.9907000064849854


Sentiment Classification(Binary Classification) RNN

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [34]:
num_words= 10000 #load top 10000 frequent words
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=num_words)

# pad sequences to equal length
maxlen = 200
X_train = pad_sequences(X_train,maxlen=maxlen)
X_test = pad_sequences(X_test,maxlen=maxlen)


17464789/17464789 [==============================] - 3s 0us/step


In [36]:
# BUild RNN MOdel

model = Sequential([
    Embedding(input_dim=num_words,output_dim=32,input_length=maxlen),
    SimpleRNN(32),
    Dense(1,activation='sigmoid')
])

In [37]:
# compile and train
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,batch_size=64,validation_split=0.2)

Epoch 1/5
313/313 [==============================] - 11s 32ms/step - loss: 0.5570 - accuracy: 0.7003 - val_loss: 0.3840 - val_accuracy: 0.8338
Epoch 2/5
313/313 [==============================] - 10s 31ms/step - loss: 0.3593 - accuracy: 0.8480 - val_loss: 0.3985 - val_accuracy: 0.8264
Epoch 3/5
313/313 [==============================] - 10s 31ms/step - loss: 0.2508 - accuracy: 0.9053 - val_loss: 0.3851 - val_accuracy: 0.8536
Epoch 4/5
313/313 [==============================] - 10s 31ms/step - loss: 0.1744 - accuracy: 0.9370 - val_loss: 0.4051 - val_accuracy: 0.8452
Epoch 5/5
313/313 [==============================] - 9s 30ms/step - loss: 0.1040 - accuracy: 0.9646 - val_loss: 0.4684 - val_accuracy: 0.8382


In [38]:
loss,acc = model.evaluate(X_test,y_test)
print(acc)

782/782 [==============================] - 5s 6ms/step - loss: 0.4775 - accuracy: 0.8317
0.8316799998283386


Embedding layer converts word indices to dense vectors.

SimpleRNN processes the sequence.

For better performance, we can use LSTM or GRU, which are advanced RNN variants that handle long-term dependencies.

In [41]:
# test with new data

word_index =imdb.get_word_index()

# Invert it to get word -> index mapping
word_to_id = {k: (v + 3) for k, v in word_index.items()}
word_to_id["<PAD>"] = 0
word_to_id["<START>"] = 1
word_to_id["<UNK>"] = 2
word_to_id["<UNUSED>"] = 3

1641221/1641221 [==============================] - 1s 1us/step


In [45]:
# Convert New Text to Index Sequence
def encode_review(text):
    tokens = text.lower().split()
    return [1] + [word_to_id.get(word, 2) for word in tokens]  # 1 = <START>, 2 = <UNK>

# Example new review
new_review = "The movie was boring"
encoded = encode_review(new_review)

# Pad to the same length as training data (e.g., 200)
padded = pad_sequences([encoded], maxlen=200)


In [46]:
prediction = model.predict(padded)
print(prediction)
# Interpret result
if prediction[0] > 0.5:
    print("Positive Sentiment")
else:
    print("Negative Sentiment")

1/1 [==============================] - 0s 26ms/step
[[0.0581688]]
Negative Sentiment
